name: vivo_desafio_github_searcher
description: "Projeto feito para desafio VIVO."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  fl_chart: ^0.65.0
  mocktail: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
